app = 'odin-social-backend'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[metrics]
  port = 9100
  path = "/metrics"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
