# fly.toml app configuration file generated for odin-social-backend on 2024-07-03T15:27:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'odin-social-backend'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[metrics]
  port = 9100
  path = "/metrics" # default for most prometheus exporters

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
